### ISSUE TITLE
Run the program in loop until they want to stop (Calculator)

### ISSUE THREAD

**Issue by yashkite** [yashkite/Code-Practice#22]
Run the program in loop until they want to stop (Calculator)

code path
[Small Projects/Python/Calculator/run.py](https://github.com/yashkite/Code-Practice/blob/main/Small%20Projects/Python/Calculator/run.py)

**Comment by bakanabaka** [comment]
I have done solved this issue, check if its correct

**Comment by yashkite** [comment]
close #22 because of PR #25
