### ISSUE TITLE
Make a Code more object oriented (Coffee Maker)

### ISSUE THREAD

**Issue by yashkite** [yashkite/Code-Practice#29]
Make a Code more object-oriented (Coffee Maker)

source code:
[Small Projects/Python/Coffee Maker/run.py](https://github.com/yashkite/Code-Practice/blob/main/Small%20Projects/Python/Coffee%20Maker/run.py)

**Comment by sricharan200** [comment]
@yashkite, can you assign me to this issue?

**Comment by real-zephex** [comment]
Hey @yashkite 
Can you please elaborate more on what you mean by "make it more object oriented"?

**Comment by yashkite** [comment]
Using OOPs concepts so we can implement test cases easily

**Comment by real-zephex** [comment]
> Using OOPs concepts so we can implement test cases easily

Alright, will get to this soon.

**Comment by sricharan200** [comment]
@yashkite , I have made the pull request. Kindly look into it

**Comment by yashkite** [comment]
@sricharan200 changes requested

**Comment by yashkite** [comment]
solved by #33
