### ISSUE TITLE
Write the Test Cases for 100% code Coverage

### ISSUE THREAD

**Issue by yashkite** [yashkite/Code-Practice#8]
Write the Test Cases for 100% code coverage for the following file:
Small Projects/Calculator/calculator/src/main/java/com/example/calculator/App.java

**Comment by cosyflower** [comment]
Hi, @yashkite 
I'd like to work on this issue. I can handle with AssertJ, JUnit and Mockito.
kindly assign it to me!

**Comment by yashkite** [comment]
Go ahead 🙂

**Comment by yashkite** [comment]
Go ahead with junit

**Comment by cosyflower** [comment]
@yashkite
Can I ask some questions??

1. I've forked your repo and recognize that main functions are in "private static"

Can I change to public with methods related to calculation such as "add", "subtract", "multiply", "divide"
( If still in private, I can't test these calculations or should make different public static methods for test codes?? )

2. I also found that this application doesn't have any validation during input numbers..
Just write test within normal cases??

**Comment by yashkite** [comment]
You're good to go with anything unless it gets against the main idea and code readability

**Comment by cosyflower** [comment]
Understood. In the beginning, I will create a separate package for the test code and create methods. 

I will inform you about the upcoming steps gradually.

**Comment by yashkite** [comment]
this merge closes #8
